version: 2
project_name: noxdir

before:
  hooks:
    - go mod tidy

signs:
  - artifacts: checksum
    cmd: gpg
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

#chocolateys:
#  - name: noxdir
#    package_source_url: https://github.com/crumbyte/noxdir
#    owners: crumbyte
#    title: "Terminal utility for visualizing file system usage."
#    authors: crumbyte
#    project_url: https://github.com/crumbyte/noxdir
#    url_template: "https://github.com/crumbyte/noxdir/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
#    copyright: 2025–2025 Crumbyte
#    license_url: https://github.com/crumbyte/noxdir/blob/main/LICENSE
#    require_license_acceptance: false
#    project_source_url: https://github.com/crumbyte/noxdir
#    docs_url: https://github.com/crumbyte/noxdir/blob/main/README.md
#    tags: "cli tui disk-usage analyzer filesystem cross-platform terminal"
#    summary: "Terminal utility for visualizing file system usage."
#    description: |
#      {{ .ProjectName }} is a high-performance, cross-platform command-line tool
#      for visualizing and exploring your file system usage.
#    release_notes: "https://github.com/crumbyte/noxdir/releases/tag/v{{ .Version }}"
#    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
#    source_repo: "https://push.chocolatey.org/"
#    skip_publish: true

nfpms:
  - package_name: noxdir
    file_name_template: "{{ .ConventionalFileName }}"
    homepage: "https://github.com/crumbyte/noxdir"
    description: "Terminal utility for visualizing file system usage."
    maintainer: crumbyte <oleksiivodotyiets@gmail.com>
    license: MIT
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux
    contents:
      # man page
      - src: ./man/noxdir.1
        dst: /usr/share/man/man1/noxdir.1
      # completions
      - src: ./completion/noxdir.bash
        dst: /usr/share/bash-completion/completions/noxdir
      - src: ./completion/noxdir.zsh
        dst: /usr/share/zsh/site-functions/_noxdir
      - src: ./completion/noxdir.fish
        dst: /usr/share/fish/vendor_completions.d/noxdir.fish
      # docs
      - src: ./LICENSE
        dst: /usr/share/doc/noxdir/LICENSE
      - src: ./README.md
        dst: /usr/share/doc/noxdir/README.md

builds:
  - id: noxdir
    binary: noxdir
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [ tar.gz ]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [ zip ]
    files:
      - LICENSE*
      - README*
      - man/*
      - completion/*

homebrew_casks:
  - name: noxdir
    binary: noxdir
    manpages:
      - man/noxdir.1
    completions:
      bash: completion/noxdir.bash
      zsh: completion/noxdir.zsh
      fish: completion/noxdir.fish
    directory: Casks
    homepage: "https://github.com/crumbyte/noxdir"
    description: "Terminal utility for visualizing file system usage."
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noxdir"]
          end
    repository:
      owner: crumbyte
      name: homebrew-noxdir
      branch: main
      token: "{{ .Env.GH_PAT }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "README.MD"
      - "^docs:"
      - "^test:"

release:
  github:
    owner: crumbyte
    name: noxdir
  name_template: "{{.ProjectName}}-v{{.Version}}"
